/* eslint-disable @typescript-eslint/no-explicit-any */
import { Page, Document, StyleSheet } from "@react-pdf/renderer";
import PDFHeader from "./PDFHeader";
import PDFTable from "./PDFTable";
import PDFFooter from "./PDFFooter";
import { FC } from "react";

const styles = StyleSheet.create({
    page: {
        padding: 20,
    },
    content: {
        margin: 10,
        width: "100%",
    },
});

interface MyDocumentPropsType {
    headerData: any;
    data: any;
}

const MyDocument: FC<MyDocumentPropsType> = ({ headerData, data }) => {
    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <PDFHeader title="Tracker money asm" />
                <PDFTable headers={headerData} data={data} />
                <PDFFooter text="Generated by Tracker money asm, 2024" />
            </Page>
        </Document>
    );
};

export default MyDocument;
